name: test some staff

on: push
jobs: 
  logging:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install gcc
        run: sudo apt-get update && sudo apt-get install -y g++

      - name: Compile
        run: g++ -s -O3 -o main.exe main.cpp

      - name: Run app
        run: ./main.exe


